services:
  analysis:
    image: bangele1/analysis-in-a-box-rocker:SerranoGomezAngele2026
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/project
    working_dir: /home/rstudio/project
    environment:
      - PASSWORD=rstudio
      - CMDSTAN=/opt/cmdstan/cmdstan-2.38.0
