---
bibliography: [references-manuscript.bib, r-references.bib]
---

In the present study, we reported three experiments using a novel flanker manipulation involving articles in order to investigate whether Spanish readers process articles and nouns as a single unit. The flankers were always articles that could either be in agreement (concordant) or discordant with the target stimulus (in Experiment 1, we also included a no-flanker control condition). All information required for the tasks was provided by the central target stimulus, such that the flanker articles were irrelevant and should have been ignored by an ideal observer. Despite this, there was clear evidence of the participants processing the flankers in Experiment 1 (a grammatical gender categorization task) and Experiment 2 (a lexical decision task), as indicated by the effect of the flankers on response time in both experiments and on accuracy in Experiment 1. This suggests that, at least under some circumstances, readers cannot help but process articles and nouns as a unit. However, in Experiment 3 (a semantic categorization task), we found no evidence for a flanker effect, suggesting that, in this case, the participants were able to ignore the flankers. There are two possible explanations for this difference in results between the experiments. First, it is possible that readers were able to process only the nouns in Experiment 3, ignoring the articles. The question is why they were not able to do the same in Experiments 1 and 2. It is not clear how a semantic categorization task would cause readers to engage in serial processing rather than parallel processing. Second, it is possible that the participants did process the articles in Experiment 3, but, since the article information was not at all relevant for the task, it did not interfere with their responses.

## Implications for models of word recognition: Does lexical processing precede semantic processing?

There are clear implications of these results for models of visual word recognition. The most important finding, at the level of individual word recognition, is that the article flanker manipulation appears to interfere with a syntactic/lexical task (grammatical gender categorization) and a pure lexical task (lexical decision), but not with a semantic task. This seems to contradict models that assume that lexical processing is a necessary pre-requisite for semantic processing [with the exception of the model by @sá-leite2024; see below]. For example, the original Logogen model [@morton1969] made the assumption that, once the logogen for a particular word is activated, all information about the word is active. This includes orthographic, syntactic, and semantic information. Similarly, all these sources of information can activate the logogen. It is not clear why the incompatible syntactic information from the article flanker should inhibit this activation process during a lexical and syntactic task, but not during a semantic task. Similarly, in Forster's Autonomous Search Model [@forster1976], all information about a lexical entry becomes available once the word is found in one of the access files. While the interactive activation model [IAM; @rumelhart1982; @mcclelland1981] does not have an explicit semantic layer, it predicts that, during word recognition, activation spreads from visual feature nodes to letter nodes to word nodes (bottom-up processing), but the higher-level nodes can feed back activation to lower-level nodes (top-down processing). This is how the IAM explains the word superiority effect [@reicher1968; @wheeler1970], but it also means that it is unlikely that a hypothetical semantic layer would be unaffected by disruption on the lexical layer caused by the discordant article flanker condition.

Compared to models that propose a particular, all-or-nothing moment of "lexical access" at which all information about a word becomes available simultaneously (and before which no top-down information is available), our results are more compatible with distributed models such as the Triangle model [@seidenberg1989], a model of word recognition with sets of orthographic, phonological, and semantic units, which are all connected by hidden units. There is no central "logogen"-type representation; rather, the information about a word that is available is represented by the simultaneous activation of the different nodes, and a reader's knowledge about words is represented by the connections between the nodes and the hidden layers. While the triangle model does not have an explicit syntactic layer, one could easily imagine an additional set of units representing the grammatical gender of a word. Alternatively, the knowledge about grammatical gender could be implicit in the knowledge about the context in which words occur ("mesa" occurs frequently in the context of "la" and "una", but never in the context of "el" or "un"). If participants perform the semantic task by exclusively evaluating the state of the semantic units (which are activated by the orthographic information about the noun), their performance might not be affected by the discordant flankers. On the other hand, the grammatical gender categorization task directly relies on information about the word context, and the lexical decision task may, more indirectly, rely on a general "error signal" which is triggered by the discordant article flankers.

Uniquely, the model by @sá-leite2024 both involves a form of lexical access (the activation of the word lemma), and an explicit representation of word gender. Our results confirm central predictions of the model, such as the prediction that articles influence the processing of words in languages with grammatical gender and that the explicit gender categorization task shows much stronger effects of article-noun agreement than the lexical decision task. While the model is agnostic about the timing of the processing of articles and nouns, our results show that articles and nouns are indeed processed simultaneously.

## Implications for models of reading: Is word recognition serial or parallel?

Our findings suggest a differentiated picture regarding the processing of articles during reading: The presence of an incorrect article most likely does not interfere much with processing the meaning of the subsequent noun, but the grammatical gender information may become relevant as a reader tries to process the syntactic structure of a sentence as a whole. This is precisely what @serrano-carot2026 observed in a gaze-contingent display change experiment similar to that done by @angele2013b, where the preview for an article in Spanish sentences was manipulated such that it could be either agree (be concordant) with the subsequent noun or disagree with it (be discordant): There was no immediate effect of the discordant article previews on ongoing processing, as reflected by skipping probability for the article, but later fixation time measures showed a clear inhibitory effect of the discordant previews further downstream. In principle, and always with the caveat that a flanker task is of course not the same as sentence reading, our results (especially those of Experiments 1 and 2) are compatible with a parallel account of reading, where articles and nouns are processed at the same time. However, Experiment 3 shows that such parallel processing does not always have to be reflected in behavior. Alternatively, our results are also compatible with a multi-constituent unit approach such as those proposed specifically for articles and nouns by @radach1996 and, more generally, for frequent combinations of lexical units by @zang2019, predicting that articles and nouns are processed as one single unit. Multi-constituent units themselves may well be processed either serially or in parallel.

## Conclusions

In summary, using our novel article flanker manipulation, we found evidence for obligatory joint processing of articles and nouns. However, this only seems to be the case during certain syntactic and lexical tasks and not during a purely semantic task. Our results are compatible with distributed models of word recognition such as the Triangle model, but less so with models that assume a specific moment of "lexical access", with the exception of the model by @sá-leite2024. During sentence reading, our results suggest that articles could be processed together with the subsequent nouns, but that the consequences of this processing may not become apparent in eye-movement behavior until the sentence is syntactically integrated. In other words, it may not be more difficult to determine that "el mesa" is a piece of furniture, but it may be more difficult to know what role "el mesa" plays in a sentence compared to "la mesa".

## Future directions

Apart from the obvious possibility of performing the experiments in different languages (especially languages with a case system like German), future studies might investigate the article flanker effect with different populations. @arnon2012 investigated how L2 speakers acquired grammatical gender in an artificial language and suggested that one of the reasons adult L2 learners struggle with acquiring a new language is that they learn vocabulary in isolation rather than in context and that contextual learning results in better outcomes. Perhaps the performance of L2 learners on the article flanker task might not only be related to their proficiency, but also to their tendency of processing input in context. In other words, L2 learners with a stronger article flanker effect may not just be more proficient, but may also be more efficient learners. Similarly, it would be very interesting to study how beginning readers perform on the article flanker task in their L1. In general, processing efficiency of the target word should be lower in beginning readers (and low-proficiency L2 readers), leaving less capacity for processing the flankers. However, faster learners may be more sensitive to the context and thereby to the article flankers. Future studies could also investigate whether this article flanker effect is limited to definite articles or whether it applies to indefinite articles as well ("una mesa una", "a table a", vs. "un mesa un"). There is also an open question as to whether this effect is restricted to gender agreement or if it applies to number agreement as well: would there be a difference between "la mesa la" and "las mesas las"? What if both number and gender agreement are manipulated ("la mesa la" vs. "los mesas los")? Another important question is whether this effect is specific to articles or whether it would also occur for other parts of speach that need to be in agreement with the noun, such as plural possessives or demonstratives. For example, would we see the same difference between "nuestra mesa nuestra" ("our table our") and "nuestro mesa nuestro" as we did for the concordant and discordant article flankers? Would we see the same for "esta mesa esta" ("this table this") compared to "este mesa este"? We could ask the same question for adjectives: Would there be a difference between "roja mesa roja" ("red table red") and "rojo mesa rojo"? Finally, as this was a purely behavioral experiment, we did not control the participant’s gaze position. It may be interesting to replicate this experiment using eye-tracking (either in the laboratory or online) in order to see whether participants always fixate the target word or whether they sometimes fixate the flankers instead (the presentation duration of 150 ms was not sufficient time for participants to move their eyes), and how performance on the task varies depending on fixation location. In summary, we have introduced a new experimental paradigm, the Article Flanker Paradigm, that allows us to study under which conditions readers obligatorily process the syntactic features of articles presented next to the target word. There is ample scope for extending this paradigm to investigate how native and non-native readers with different native languages process articles and other words that are syntactically marked for grammatical gender, number, and case.
