---
bibliography: [references-manuscript.bib, r-references.bib]
---

Articles are fundamental building blocks of many languages, particularly those that are members of the Indo-European family. Articles belong to the syntactic category of determiners and are commonly used to indicate the grammatical definiteness of a noun phrase. Definiteness has been the subject of extensive investigation, both in philosophy [@russell1905] and linguistics [e.g., @lyons1999]. Very broadly speaking, a definite noun phrase refers to a specific and known object or entity, while an indefinite noun phrase refers to a newly introduced or previously unspecified object or entity.

In many languages, nouns also have a grammatical gender [@corbett1991]. The grammatical gender often corresponds to the semantic or natural gender of a noun (for example, a noun referring to a male individual, e.g. "niño", "boy", in Spanish, will usually be of masculine grammatical gender, while a noun referring to a female individual, e.g. "niña", will often be of feminine grammatical gender). Importantly, there are languages, such as German and most Romance languages, where every noun has a grammatical gender, even if it does not have a semantic or natural gender. For example, in Spanish, "piedra" is feminine, even though its meaning "stone" does not correspond to any natural gender. In many languages with grammatical gender, the articles are gendered as well, and every noun needs to be accompanied by the article corresponding to its grammatical gender (as well as number, and, in languages like German, case). This is known as agreement [for an overview, see, e.g., @wechsler2003]. In practice, this means that a Spanish feminine noun such as *mesa* (table) needs to be preceded by the feminine definite article *la* or the feminine indefinite article *una*, and using the masculine articles, as in *el\* mesa* or *un\* mesa,* is incorrect. When a noun is presented together with a discordant article, this leads to delayed processing, known as the *gender agreement effect*, as measured in tasks such as picture naming [e.g., @jescheniak1999], auditory lexical decision [e.g., @dahan2000] as well as event-related potentials in EEG [e.g., @barber2005; @alemánbañón2016]. For a review of this research, see @friederici1999 and @beatty-martínez2019; for a general review on how word identification and lexical access are affected by grammatical gender, see @sá-leite2024. In some languages such as Spanish, Portuguese, and Italian, the gender of most nouns is obvious from the noun ending. For example, the "-a" ending of "mesa" indicates that it is feminine. Not all words in a language are transparent (for example, *raíz* in Spanish is feminine even though it lacks an "-a" ending), and languages differ in terms of their general degree of transparency [@sá-leite2024a]. For example, Dutch noun endings are much less informative in terms of grammatical gender than Portuguese noun endings [@sá-leite2024a]. Also, grammatical gender does not necessarily correspond to the natural or semantic gender: in German, the grammatical gender *das Mädchen* (the girl) is neuter since the diminutive *-chen* automatically results in a neuter noun (similar examples are *das Männchen* – the little man – or *das Weib* - an old-fashioned word for woman, related to the English *wife*). Similarly, in Italian, there are some nouns that are always grammatically feminine such as *la guardia* (the guard) or *la spia* (the spy), even if they refer to a male guard and a male spy. In Spanish, *la víctima* (the victim) is similar in that it is always feminine, even if the person it refers to is male (the equivalent in German, *das Opfer*, is always neuter). In summary, there is not always a morphological or semantic link between a word and its grammatical gender. However, the article is very closely associated with the grammatical gender of a word^[An exception to that rule are feminine words in Spanish that start with "a" and have the stress on the first syllable. In singular, these are preceded by the masculine article, such as "el agua" (the water). These words are considered to be feminine by the Real Academia Española [@rae_dpd], but real-world examples show that there may be some ambiguity among native speakers [@eddington2008]. Because of this, no words of this category were included in the materials for the present study.]

## Are written articles and words processed in parallel?

Because articles and nouns are so closely associated, one might wonder if they are processed as a single unit when presented in written text. This question is particularly relevant considering the ongoing debate on whether word identification during reading is serial, i.e., occurs one word at a time, or parallel, with multiple words being identified at the same time [for an overview of the debate, see @reichle2009; @snell2019; @white2019; @schotter2019]. The idea that written articles and nouns are processed as one unit was first put forward by @radach1996 as the *Word Grouping Hypothesis*. In a large eye-movement data set, Radach observed that groups of short words followed by longer words, such as groups of articles and nouns (e.g., *the table*) are targeted as if they were one longer word, with fixations aimed at the center or slightly left of center [the *preferred viewing location,* @rayner1979] of the entire group (e.g. the *t* or the *a* in *table*), rather than the reader targeting the article and the noun separately*.* This often results in the short word being not fixated at all (i.e., being skipped), which is a common observation in studies of eye-movements during reading. @radach1996 claimed that this happened for all groups of shorter words followed by longer words, not just articles and nouns. @drieghe2008 performed an experiment to test this claim for different types of short words, comparing articles (*the*) to other high-frequency three-letter words (e.g., *two*) and to longer words (e.g., *other*) in the exact same sentence context. @drieghe2008 replicated @radach1996's findings for the articles, but not the other short words; however, they argued that their findings could be explained by the high skipping rate associated with articles due to their short length and high word frequency rather than due to a different saccade targeting mechanism. Still, @drieghe2008's results are compatible with articles and nouns being processed jointly.

## Theoretical approaches to grammatical gender processing in articles and nouns

Recently, the idea of certain groups of familiar words such as *teddy bear* being processed as a single unit has received renewed attention due to the Multi-Constituent Unit (MCU) hypothesis [@zang2019; see also @cutter2014; @yu2016]. The MCU assumes that frequently co-occurring words can be processed as a single unit if they all refer to the same concept. At the unit level, processing is still serial. The MCU hypothesis is particularly relevant for reading in Chinese, where there are many idioms and common phrases whose characters co-occur so frequently that they can be considered lexicalized units (and, indeed, many Chinese dictionaries have entries for common three and four character idioms). Following this perspective, sequences of common articles and nouns (such as *la mesa*) may well occur frequently enough to be considered multi-constituent units.

From a perspective of word recognition and lexical access, @sá-leite2024 propose a dual-route, interactive-activation account based on the AUSTRAL model of word identification [@taft2023]. In the AUSTRAL model, there are three levels of representation: the word form level, which contains common letter combinations (such as PLAY, CORN, and ER), the lemma level, where activation from word forms spreads to semantically meaningful lemma units (which can be both multimorphemic words, such as "player" and single morphemes, such as "play", "corner" and the suffix "-er"). The first lemma to reach a set threshold of activation is selected. Importantly, lemmas can activate each other depending on their semantic features: "player" is activated indirectly through the lemmas "play" and "-er", as it is a multimorphemic word, while a monomorphemic word such as "corner" is represented as a single node activated by the word forms (but not lemmas) CORN and ER. The stimulus CORNER activates both the lemma "corn" and the lemma "corner", but since there is no strong connection between the lemmas "corn" and "-er", the correct lemma "corner" is ultimately selected. Finally, the lemmas are connected to their associated concepts at the semantic level. @sá-leite2024 expand the AUSTRAL model by additionally assuming the existence of a syntactic level with nodes representing the grammatical gender of a word (for Spanish, this would be a masculine and a feminine node). Just as multimorphemic words in the original AUSTRAL model, gender-transparent words are segmented into their root morpheme (e.g. "mes") and the ending ("-a"), while gender-opaque words such as "raíz" are processed as a whole. The grammar nodes can receive input both from the ending morphemes for transparent words (sublexical route) and from the complete word lemmas for transparent and opaque words (lexical route). Additionally, they receive input from any articles that are present, although the extent of this input and its importance depend on the language and the regularity and transparency of the noun. In Spanish, where most nouns are transparent in terms of gender, Sá-Leite and Lago's [-@sá-leite2024] modified AUSTRAL model does not predict participants relying on articles when making grammatical gender decisions about nouns. However, the existence of a connection between article lemmas and grammatical gender nodes means that, in principle, the presence of articles, especially discordant ones, may still affect the processing of the noun. Additionally, the model makes predictions about the impact of articles on different tasks (see below). Since a gender categorization task (or a grammaticality judgment) requires directly querying the gender nodes, it should be most strongly affected by article-noun agreement (or the lack thereof). On the other hand, in a lexical decision task, the sublexical route might be less important than the lexical route, leading to smaller agreement effects.

## Early detection of syntactic violations

Sá-Leite and Lago's [-@sá-leite2024] model does not make explicit claims about the time course of grammatical gender processing, but there is evidence from behavioral and ERP studies that syntactic violations can be detected very quickly and unconsciously. @batterink2013 presented sentences with or without syntactic violations (e.g. "We drank Lisa’s by\* brandy the fire in the lobby" vs. "We drank Lisa’s brandy by the fire in the lobby" using rapid serial visual presentation (RSVP) in the center of the screen while asking participants to report whether they had detected a syntactic violation or not. They found that syntactic violations were associated with an early negativity regardless of whether participants reported that they had detected them or not. Reporting the syntactic violation was associated with an additional later positivity. @lucchese2017 presented auditory stimuli in German consisting of a combination of pronoun and verb. The verb ending could either be consistent with the pronoun (e.g., "ich zeige", "I show") or inconsistent (e.g., "ich zeigen\*"). They also included stimuli with non-existing verb stems (e.g. "ich leige\*", which is not a word, but has the correct inflection, and "ich leigen\*", which has the incorrect inflection). Lucchese et al found that the syntactically incorrect verb endings resulted in early mismatch negativities compared to the standard responses, as did the stimuli with non-existing verb stems. They concluded that retrieval of words from memory and processing of their syntactic properties occur early on in processing, resulting in early mismatch signals. The preceding studies did not include the presentation of syntactical violations involving articles, however, Pyatigorskaya et al. [-@pyatigorskaya2023; -@pyatigorskaya2025] used a masked priming paradigm to present combinations of German masked and unmasked function word primes (articles and pronouns) followed by content word targets (nouns and verbs). These combinations could either be grammatical (article followed by noun, e.g. "ein Monat", "a month" or pronoun followed by verb "er hüpft", "he jumps") or ungrammatical (e.g. "er Monat", "he month" or "ein hüpft", "a jumps"). Ungrammatical combinations were associated with slower responses in a grammatical categorization task [@pyatigorskaya2023] and with a late positivity response [P600, @pyatigorskaya2025] regardless of masking, demonstrating that participants processed even the masked stimuli that they did not consciously perceive.

## Parafoveal processing of articles

Overall, the research presented in the previous paragraph shows that syntactic violations, including those involving articles, can be detected quickly when the words are presented in quick succession in the same location (RSVP and masked/unmasked priming), no matter whether there is conscious perception of the violation or not. However, we do not know if the same is true in sentence reading, where all words are presented at the same time and readers have to select where to attend overtly (through eye movements) and covertly (by allocating their visual attention). In the latter case, information about the words to be read has to be obtained from the parafovea, the area on the retina surrounding the center of vision (the fovea). Most word groups consisting of articles and nouns are too long to fit in the fovea completely, requiring parafoveal processing in order to detect syntactic violations. Parafoveal processing can be studied with the gaze-contingent display-change paradigm [@rayner1975b], which uses eye-tracking to manipulate the input readers receive of a target word within a sentence before fixating it. This is done by placing an invisible boundary to the left of a target word. While the participant’s gaze is located to the left of the target word, the target word is replaced by a preview stimulus. As the participant’s gaze moves across the boundary, the display is updated to replace the preview stimulus with the target word. This change usually takes place during a rapid eye movement known as a saccade. During saccades, the brain receives virtually no new visual information, making the display change undetectable by the participant as long as it is performed with the correct timing in relation to the saccade. The gaze-contingent display change paradigm allows an experimenter to manipulate the parafoveal information about a target word, i.e., the information that is available for pre-processing of a word before it is fixated. For example, Rayner [-@rayner1975b] found that readers processed a target word faster and fixated it for less time when they had had a correct preview of it than when the preview had consisted of random letters. Previews are related to primes, particularly to masked primes, in that they provide information about a target word ahead of the word being processed without the participant being consciously aware of them. The main difference between primes and previews is that primes are usually presented in the center of vision (the fovea), while previews are presented in the parafovea, allowing us to study parafoveal pre-processing of words during skilled sentence reading. Thanks in part to the gaze-contingent boundary paradigm, there is now a large body of research showing that parafoveal processing plays a key role in skilled and efficient reading [for a review, see @schotter2011].

One particular feature of skilled and efficient reading is that short words are often not fixated, speeding up the reading process. When making the decision of whether to fixate a word or skip it altogether, readers have to rely solely on parafoveal information. In order to study how parafoveal information about upcoming articles interacts with what a reader already knows about the sentence context, @angele2013a used the gaze-contingent display change paradigm to manipulate the previews readers received of a three-letter target verb, e.g. *ace* in *She was sure she would ace all the tests.* The preview could either be identical (*ace*), a random letter string (*fda*) or the definite article *the*. Importantly, this last preview condition resulted in a situation where readers received a parafoveal preview of the upcoming word that looked like an article (and would therefore be likely to be skipped), but appears in a position where an article would be syntactically illegal (*she would the*). If readers take the preceding sentence context into account when making a skipping decision, they should not skip a preview looking like *the* in this case. However, Angele et al.'s [-@angele2013a] results show that readers do in fact skip the target word very frequently when its preview looked like *the*, suggesting that they are unable to take the incompatibility between the preceding sentence context and the upcoming parafoveal word into account when making the decision to either fixate or skip the next word. A similar result was reported by Vieira et al. (2024). One may think that this shows that the preceding sentence context never plays a role when making a skipping decision, but this is not the case: Words that are predictable from the sentence context are reliably skipped more often than words that are not [@slattery2018; @rayner2011]. @abbott2015 tested this directly, combining Angele et al.'s [-@angele2013a] preview manipulation with a predictability manipulation for the target word (e.g. *If you are shot in the heart you will surely **die** immediately* vs. *If you are shot in the foot you will surely **die** immediately*, with *die* being the target word which, for the syntactically illegal preview, was replaced with *the*). They found that readers were still very likely to skip a syntactically illegal *the*-preview even when the actual target word *die* was highly predictable.

In a recent gaze-contingent display change study in Spanish, @serrano-carot2026 found that readers are just as likely to skip articles that are concordant with the preview of the subsequent noun, e.g. *la* in *la mesa* as they are to skip articles that are discordant with the preview of the subsequent noun, e.g. *el* in *el mesa* (participants were unaware of this manipulation because the article was replaced by the concordant article in the subsequent display change). This suggests that, despite the clear ability of readers to detect syntactic violations extremely quickly as shown by the studies discussed above, they are either unable to do this during sentence reading or the syntactic anomaly is not reflected in their immediate eye movements. There was an effect of the manipulation on fixation times on the noun, suggesting that the incorrect information about the article was not completely ignored, but it was not apparent in any of the early fixation time measures and only occurred at a very late stage (total viewing time).

This leads us to the next possible account of how articles and nouns are processed together in sentence reading. Perhaps the article is simply not normally processed at any great depth, with readers focusing their processing effort on the noun. In this account, readers merely extract the relevant information on definiteness from the article, which they can often do parafoveally, and then do not process the article any further. This would be compatible with findings involving the Missing Letter Effect [@healy1994; @koriat1993; @koriat1994; @saint-aubin2008], which indicate that, when asked to count all instances of a particular letter on a page (e.g., the letter *t*) participants are more likely to miss a letter when it is part of a high-frequency function word (e.g. the *t* in *the*) than when it is part of a lower frequency content word (e.g. the *t* in *tie*) . Similarly, @staub2019 found that readers failed to detect a repetition error involving *the* (e.g., *Amanda jumped off the the swing and landed on her feet*.) in as many as 54.2% of all trials, while repeated nouns (e.g., *jumped off the swing swing*) were noticed 90% of the time. Even only considering trials where both instances of *the* were fixated, readers still failed to report 34% of the repetitions. In summary, while readers seem to have the ability to detect syntactic violations when they are presented with words one by one in the center of vision (RSVP), this does not seem to be the case during natural reading.

## Using the Flanker paradigm to study processing of articles

Is the reason why articles seem to be processed less deeply during reading the fact that they are presented at the same time as other words and often have to be processed parafoveally? In order to investigate this question, we used the *Flanking Letters paradigm* (also referred to simply as the *Flanker paradigm*) which was introduced by @dare2013. This paradigm, which recently has become very popular in studying how parafoveal information affects foveal word identification, is an adaptation of the classic Flanker task [@eriksen1974] and involves presenting a central target word alongside a number of flanker stimuli, usually to the left and right, but also above and below the target word [e.g., @snell2018a]. If the presence and the type of the flankers influence the response time and response accuracy on a task involving the target word, most commonly the lexical decision task (LDT), this is taken as evidence in favor of parallel processing of the target and the flankers [e.g., @snell2018b; cf. @schotter2019].

So far, the Flanker paradigm has been used frequently to investigate orthographic processing by comparing the effect flankers that were orthographically related or unrelated to the target word [@dare2013; @snell2018a; @snell2018b; @snell2018c; @snell2021; @snell2025], but there are also studies that investigate the effect of syntactic congruency by manipulating whether flankers and target are the same part of speech on a syntactic categorization task [@snell2024] or by manipulating whether the flankers form a grammatical context for the target word [e.g. *this word fits* vs. *fits word this*, @vandendaele2020, @vandendaele2025]. The Flanker paradigm has also been used to study semantic processing: @meade2021 presented flankers that were either of the same semantic category as the target word (*coyote wolf coyote*) or a different semantic category (*coyote sofa coyote*). In a semantic categorization task (animal vs. not an animal), they found both slower response times and higher amplitude negative ERPs in the N400 window in the condition where the flankers were of a different semantic condition than the target word compared to the condition in which the flankers were of the same category.

## Summary

In summary, articles are ubiquitous in many languages, but we still do not know about how deeply they are processed in natural sentence reading. Skilled readers seem to mostly ignore articles both by skipping them and by failing to detect syntactic violations associated with them. This is despite there being plenty of evidence that, in studies presenting word stimuli one by one, participants detect syntactic violations very early and even unconsciously. Much of the research about articles in sentence reading has been done in English, where articles carry very little information. However, there are many languages, such as Spanish, where there has to be agreement between articles and nouns in terms of gender, number, and case (depending on the language). Despite this, it seems that, even in languages such as Spanish and Portuguese, articles are mostly ignored during sentence reading. The flanker paradigm can serve as a useful intermediary technique between RSVP, where readers are very likely to process every word since it is the only information on the screen, and natural sentence reading, where readers can choose not to fixate words and it is unclear to which degree those words are processed. By making the flanker information irrelevant to the behavioral task, we can determine if readers obligatorily process information that is parafoveally presented or if they can ignore it.

## Present study

The fact that, in languages such as Spanish, there must be gender agreement between articles and the subsequent nouns makes it possible to use the Flanker paradigm to test whether Spanish readers obligatorily process articles and nouns together. According to the *gender agreement effect*, if we show participants a noun flanked by a discordant article (e.g. *el mesa el*), this should lead to disruption in a task that relies on the joint processing of article and noun compared to either a flanker condition with concordant articles (*la mesa la*) or a control condition without flankers. We tested this in three experiments, each with a different task. These experiments also provide a direct test of the model by @sá-leite2024. In Experiment 1, we asked participants to respond based on the grammatical gender of a target noun (grammatical gender categorization task). As described above, the model by @sá-leite2024 predicts strong effects of noun-article agreement in this task, although, in a flanker task, this would only be the case if articles and nouns can be processed at the same time. In Experiment 2, participants performed a lexical decision task (LDT) on the central target stimulus, with the same flanker conditions as in Experiment 1. In an LDT, discordant flankers may either interfere with lexical access or cause a general error signal that may make it more difficult to correctly identify word stimuli. The model by @sá-leite2024 predicts a smaller effect of noun-article agreement in this implicit task than in the explicit gender categorization task. Finally, in Experiment 3, participants performed a semantic categorization task, indicating whether the target word referred to an animal or not. One might assume that the grammatical gender of the target word is irrelevant for this task, but many models of word identification assume, at least implicitly, the lexical representation of a word needs to be activated in order for it to be processed semantically. @sá-leite2024 do not make explicit predictions for semantic categorization tasks, but, given that the grammatical gender nodes are not directly linked to the semantic nodes, we would expect there to be at best a subtle, indirect effect of gender agreement on performance in the semantic categorization task.
